create table jobs(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dep_code varchar(20) NOT NULL,
    dep_job varchar(100) NOT NULL,
    description varchar(255),
    UNIQUE (dep_code, dep_job)
);

drop table jobs;

select * from jobs;
